wallets:
  governance_multisig: &governance_multisig
    type: multisig
    address: "0x457a60065050050B3e64Fcd96cFb973123D38338"
  governance: &governance
    type: default # use the accounts provided by Hardhat/Ganache
    index: 1
  gatekeeper: &gatekeeper
    type: default
    index: 2
  manager: &manager
    type: default
    index: 3
addresses:
  yop_token_contract: &yopContract "0xAE1eaAE3F627AAca434127644371b67B18444051"
  yop_nft: &yopNFT "0xe4605d46fd0b3f8329d936a8b258d69276cba264"
  rewards_wallet: &rewardsWallet "0xa06fF227302bC83D2652c29c3fb02A627B357507"
  protocol_wallet_address: &protocolWalletAddress "0xa06fF227302bC83D2652c29c3fb02A627B357507"
  # for managing the YOP staking NFT collections on OpenSea
  yop_staking_nft_opensea_admin: &yopStakingNFTAdmin "0xa06fF227302bC83D2652c29c3fb02A627B357507"
  weth_token_address: &weth_token_address "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
  wbtc_token_address: &wbtc_token_address "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  usdc_token_address: &usdc_token_address "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  dai_token_address: &dai_token_address "0x6b175474e89094c44da98b954eedeac495271d0f"
  usdt_token_address: &usdt_token_address "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  harvester_address: &harvester_address "0x457a60065050050B3e64Fcd96cFb973123D38338"
  curve_steth_pool_address: &curve_steth_pool "0xDC24316b9AE028F1497c275EB9192a3Ea0f67022"
  curve_btc_pool_address: &curve_btc_pool "0xd5BCf53e2C81e1991570f33Fa881c49EEa570C8D"
  curve_stable_pool_addresss: &curve_stable_pool "0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7"
constants:
  vault_management_fee: &vault_management_fee 200 # 2%
  strategy_performance_fee: &strategy_performance_fee 1000 # 10%
  vault_max_debt_ratio: &vault_max_debt_ratio 9500 # 95%

access_control:
  governance: *governance
  allowlist:
    # can be changed
    enabled: true
    governance: *governance
    # can be changed
    global: []
  erc1155:
    # can be changed
    enabled: true
    governance: *governance
    # can be changed
    global:
      - contract_address: *yopNFT
        token_ids: ["134", "135", "136", "503", "504", "505"]
  allowany:
    # can be changed
    enabled: true
    governance: *governance
    # can be changed
    global: true
vault_strategy_data_store:
  governance: *governance
fee_collection:
  governance: *governance
  gatekeeper: *gatekeeper
  # can be changed
  protocol_wallet: *protocolWalletAddress
  # can be changed
  default_vault_creator_fee_ratio: 0
  # can be changed
  default_strategy_proposer_fee_ratio: 0
  # can be changed
  default_strategy_developer_fee_ratio: 0
  # can be changed
  paused: false
rewards:
  governance: *governance
  gatekeeper: *gatekeeper
  wallet: *rewardsWallet
  yop_contract: *yopContract
  emission_start_time: 1640995200 # 2022-1-1-00:00:00 GMT
  # can be changed
  total_allocation_weight:
    vaults: 100
    staking: 100
  # can be changed
  vaults_allocation_weight:
    # never remove vaults for here.
    # Set the value to 0 if a vault should not receive emission anymore
    # Name needs to match the name of the vaults
    "Ethereum Genesis": 100
    "Bitcoin Genesis": 100
    "USDC Genesis": 100
    "DAI Genesis": 100
    "USDT Genesis": 100
  # can be changed
  paused: false
staking:
  name: "YOP Staking"
  symbol: "sYOP"
  governance: *governance
  gatekeeper: *gatekeeper
  uri: ""
  # can be changed
  contract_uri: ""
  owner: *yopStakingNFTAdmin
  # can be changed. Ignore the decimals.
  min_stake_amount: 100
  # can be changed
  paused: false
vaults:
  - name: Ethereum Genesis
    symbol: "yopETH"
    governance: *governance
    gatekeeper: *gatekeeper
    manager: *manager
    token_address: *weth_token_address
    # can be changed
    management_fee: *vault_management_fee
    # can be changed
    # if this value is reduced, check the allocations for strategies and make sure
    # the total of the allocations won't exceed the max value
    max_debt_ratio: *vault_max_debt_ratio
    # can be changed
    paused: false
    # can be changed
    emergency_shutdown: false
    # can add new strategies, but don't remove, and don't change orders here
    # change the allocation to 0 if the strategy is not used anymore
    strategies:
      - name: "CurveEth"
        contract: "CurveEth"
        harvester: *harvester_address
        pool: *curve_steth_pool
        # can be changed
        performance_fee: *strategy_performance_fee
        # can be changed
        allocation: 2850 #28.5%
      - name: "ConvexEth"
        contract: "ConvexEth"
        harvester: *harvester_address
        pool: *curve_steth_pool
        booster: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
        performance_fee: *strategy_performance_fee
        allocation: 6650 #66.5%
  - name: Bitcoin Genesis
    symbol: "yopBTC"
    governance: *governance
    gatekeeper: *gatekeeper
    manager: *manager
    token_address: *wbtc_token_address
    management_fee: *vault_management_fee
    max_debt_ratio: *vault_max_debt_ratio
    paused: false
    emergency_shutdown: false
    strategies:
      - name: "CurveBtc"
        contract: "CurveBtc"
        harvester: *harvester_address
        pool: *curve_btc_pool
        performance_fee: *strategy_performance_fee
        allocation: 2850 #28.5%
      - name: "ConvexBtc"
        contract: "ConvexBtc"
        harvester: *harvester_address
        pool: *curve_btc_pool
        booster: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
        performance_fee: *strategy_performance_fee
        allocation: 6650 #66.5%
  - name: USDC Genesis
    symbol: "yopUSDC"
    governance: *governance
    gatekeeper: *gatekeeper
    manager: *manager
    token_address: *usdc_token_address
    management_fee: *vault_management_fee
    max_debt_ratio: *vault_max_debt_ratio
    paused: false
    emergency_shutdown: false
    strategies:
      - name: "CurveUSDC"
        contract: "CurveStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        performance_fee: *strategy_performance_fee
        allocation: 2850 #28.5%
      - name: "ConvexUSDC"
        contract: "ConvexStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        booster: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
        performance_fee: *strategy_performance_fee
        allocation: 6650 #66.5%
  - name: DAI Genesis
    symbol: "yopDAI"
    governance: *governance
    gatekeeper: *gatekeeper
    manager: *manager
    token_address: *dai_token_address
    management_fee: *vault_management_fee
    max_debt_ratio: *vault_max_debt_ratio
    paused: false
    emergency_shutdown: false
    strategies:
      - name: "CurveDAI"
        contract: "CurveStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        performance_fee: *strategy_performance_fee
        allocation: 2850 #28.5%
      - name: "ConvexDAI"
        contract: "ConvexStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        booster: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
        performance_fee: *strategy_performance_fee
        allocation: 6650 #66.5%
  - name: USDT Genesis
    symbol: "yopUSDT"
    governance: *governance
    gatekeeper: *gatekeeper
    manager: *manager
    token_address: *usdt_token_address
    management_fee: *vault_management_fee
    max_debt_ratio: *vault_max_debt_ratio
    paused: false
    emergency_shutdown: false
    strategies:
      - name: "CurveUSDT"
        contract: "CurveStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        performance_fee: *strategy_performance_fee
        allocation: 2850 #28.5%
      - name: "ConvexUSDT"
        contract: "ConvexStable"
        harvester: *harvester_address
        pool: *curve_stable_pool
        booster: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
        performance_fee: *strategy_performance_fee
        allocation: 6650 #66.5%

