name: Contract Sizer

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - v2
    paths:
      - "contracts/**"
  pull_request:
    branches:
      - main
      - v2
    paths:
      - "contracts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-contract-sizer:
    name: Run Contract Sizer
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Contract Sizer
        run: npx hardhat size-contracts
