name: Solidity Hint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "contracts/**"
  pull_request:
    branches:
      - main
    paths:
      - "contracts/**"

jobs:
  sol-hint:
    name: Run Solhint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Solhint
        run: npx solhint 'contracts/**/*.sol'
