name: Test & Coverage

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-coverage:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "npm"

      - name: Installing dependencies
        run: npm ci

      - name: Generate Types
        run: npx hardhat typechain

      - name: Run unit test
        run: npx hardhat test ./test/unit/**/*.ts

      - name: Run integration test
        run: npx hardhat test ./test/integration/**/*.ts
        env:
          ENABLE_FORKING: true
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Run coverage
        run: |
          export NODE_OPTIONS="--max_old_space_size=6144"
          npx hardhat coverage

      # may enable this again when the repo becomes open
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.github_token }}
