name: Test & Coverage

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main, v2]
    paths:
      - "contracts/**"
      - "test/**"
  pull_request:
    branches: [main, v2]
    paths:
      - "contracts/**"
      - "test/**"
      - ".solcover.js"
      - ".github/workflows/test_coverage.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Installing dependencies
        run: npm ci --cache

      - name: Generate Types
        run: npx hardhat typechain

      - name: Run unit test
        run: npm run test/unit
        env:
          RUN_TEST_IN_PARALLEL: true

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Installing dependencies
        run: npm ci --cache

      - name: Generate Types
        run: npx hardhat typechain

      - name: Run coverage
        run: |
          export NODE_OPTIONS="--max_old_space_size=6144"
          npx hardhat coverage

  integration-test:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Installing dependencies
        run: npm ci --cache

      - name: Generate Types
        run: npx hardhat typechain

      # this will help reduce the time it is taking to run the integration tests
      # by caching all of the requests made by Ganache when forking
      - name: Restore Network Fork Cache
        uses: actions/cache@v3
        with:
          path: |
            ./cache/hardhat-network-fork/network-1
          key: mainnet-fork-request-cache

      - name: Run integration test
        run: |
          export NODE_OPTIONS="--max_old_space_size=6144" 
          npm run test/integration
        env:
          RUN_TEST_IN_PARALLEL: true
          ENABLE_FORKING: true
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      # may enable this again when the repo becomes open
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.github_token }}
