# This job can be used to propose changes to Rinkeby testnet contracts.
# NOTE: this should only be used to make configuration changes to existing contracts, and can't be used to deploy contracts (yet).
# It will only be triggered when the `config-rinkeby-staging.yaml` file is changed.
# In the PR, the job will only run the command in dry-run mode and only print out the changes in the console.
# Once the PR is merged, the job will then propose the changes to the Gnosis governance safe, and the governance can then approve and execute transaction.
name: Update Rinkeby Config

on:
  # allow trigger job manually
  workflow_dispatch:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - "deployment-config/config-rinkeby-staging.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "deployment-config/config-rinkeby-staging.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-mainnet-config:
    name: Update Rinkeby Config
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile Contracts
        run: npx hardhat compile

      # This is a PR will only trigger the dry-run
      - name: Update Rinkeby Config (dry-run)
        run: ./node_modules/.bin/ts-node --files ./scripts/deploy-by-config.ts --config ./deployment-config/config-rinkeby-staging.yaml --deploy false --update true --dryrun true  --env rinkeby-staging
        env:
          HARDHAT_NETWORK: rinkeby
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

        if: github.event_name == 'pull_request'

      # It's not a PR, so propose the changes to the governance safe
      - name: Update Rinkeby Config
        run: ./node_modules/.bin/ts-node --files ./scripts/deploy-by-config.ts --config ./deployment-config/config-rinkeby-staging.yaml --deploy false --update true --dryrun false  --env rinkeby-staging
        env:
          HARDHAT_NETWORK: rinkeby
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TESTNET_SIGNER_KMSID: ${{ secrets.TESTNET_SIGNER_KMSID }}
        if: github.event_name != 'pull_request'
